[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules','lib']
test= 'test/fuzz/'
cache_path = 'forge-cache'

[fuzz]
runs = 5000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config